### ISSUE TITLE
Algorithm 11.5 (pg. 207)

### ISSUE THREAD

**Issue by AndreTkacenko** [algorithmsbooks/optimization#90]
Near the bottom of the code for Algorithm 11.5 on pg. 207, I believe the line

`c'' = c'`

should instead be

`c'' = vcat(c, zeros(m))`

**Comment by tawheeler** [comment]
Well this certainly is a fantastic find! What was additionally interesting is why this wasn't caught in testing. I dug into it, and it turns out that the one test we had happened to find the optimum despite c'' being totally incorrect:

```
    A = Float64[1   1 1 0;
                2 0.5 0 1]
    b = Float64[5, 8]
    c = Float64[-3, -2, 0, 0]
    LP = LinearProgram(A, b, c)
    x = minimize_lp(LP)
    @test x[3:4] == [0,0]
    @test isapprox(x[1], 11/3, atol=1e-8)
    @test isapprox(x[2],  4/3, atol=1e-8)
```

I have now added additional testing that does error out with the old implementation, and updated the book. Thank you!

**Comment by mykelk** [comment]
Thanks @tawheeler and @AndreTkacenko !
